version: 2
jobs:
  build:
    working_directory: ~/common
    docker:
      - image: circleci/python:3.6.8-node-browsers
    steps:
      - checkout
      - run:
          name: "Install Python dependencies"
          command: |
            pip install virtualenv
            virtualenv ../venv
            source ../venv/bin/activate
            pip install -r requirements.txt
            python setup.py develop
      - run:
          name: "Test Python"
          command: |
            source ../venv/bin/activate
            pytest tests/
      - run:
          name: "Lint Python"
          command: |
            source ../venv/bin/activate
            flake8 common/
